---
title: "File Being Called"
author: "Barry DeCicco"
date: "2022-12-15"
output: html_document
params:
  year: 2018
  start_date: "2022-01-01"
  end_date:   "2022-21_31"
  region: Europe
  data: file.csv
---

```{r setup-2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Declare location of this script relative to the project root directory.
here::i_am(path = "inst//File_Being_Called.Rmd")
```

```{r load-packages-2, echo=FALSE, include=FALSE}
# Load Packages & Set Package Options
library(xfun)         # for Rscript_call()
library(devtools)     # for session_info()
library(rstudioapi)   # for versionInfo()
library(here)         # for here()
library(rmarkdown)    # for render()
library(knitr)        # for kable()
library(lubridate)    # for today()

```



# Parameters

This file has a list of parameters which start it.  They can be changed.
Here are the parameters:

<strong><h4>The Year is: `r params$year`</h4></strong>

<strong><h4>The Start Date (for reporting) is: `r params$start_date`</h4></strong>

<strong><h4>The End Date (for reporting) is:  `r params$end_date`</h4></strong>

<strong><h4>The Region is: `r params$Europe`</h4></strong>

<strong><h4>The Data File is: `r params$file.csv`</h4></strong>


  
  
  
  
